apiVersion: apps/v1
kind: Deployment
metadata:
  name: node_js_002
  labels:
    app: node_js_002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node_js_002
  template:
    metadata:
      labels:
        app: node_js_002
    spec:
      containers:
      - name: node_js_002
        image: bacdocker/nodejswebappexam:v1  
        ports:
        - containerPort: 3000
