apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-002
  labels:
    app: node-js-002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-002
  template:
    metadata:
      labels:
        app: node-js-002
    spec:
      containers:
      - name: node-js-002
        image: bacdocker/nodejswebappexam:v1  
        ports:
        - containerPort: 3000
