apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-js-002
  name:  node-js-002
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-js-002
