apiVersion: v1
kind: Service
metadata:
  labels:
    app: node_js_002
  name:  node_js_002
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: node_js_002
